import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { Navbar } from "../components/Navbar";
import HeroBg from "../assets/images/hero.png"
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

export default function Home() {
  return (
    <div>
      <div className="bg-cover bg-no-repeat bg-center  px-20  bg-my_bg_image md:h-screen pb-10 ">
        <Navbar />
        <Head>
          <title>Plugbay</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className="mt-40 px-20 pb-10">
          <div className="flex">
            <div className="flex flex-col mr-8 pt-12 space-y-3">
              <div>
                <span className="w-5">
                  <svg
                    className="fill-primary font-bold"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 448 512"
                  >
                    <path d="M224.1 141c-63.6 0-114.9 51.3-114.9 114.9s51.3 114.9 114.9 114.9S339 319.5 339 255.9 287.7 141 224.1 141zm0 189.6c-41.1 0-74.7-33.5-74.7-74.7s33.5-74.7 74.7-74.7 74.7 33.5 74.7 74.7-33.6 74.7-74.7 74.7zm146.4-194.3c0 14.9-12 26.8-26.8 26.8-14.9 0-26.8-12-26.8-26.8s12-26.8 26.8-26.8 26.8 12 26.8 26.8zm76.1 27.2c-1.7-35.9-9.9-67.7-36.2-93.9-26.2-26.2-58-34.4-93.9-36.2-37-2.1-147.9-2.1-184.9 0-35.8 1.7-67.6 9.9-93.9 36.1s-34.4 58-36.2 93.9c-2.1 37-2.1 147.9 0 184.9 1.7 35.9 9.9 67.7 36.2 93.9s58 34.4 93.9 36.2c37 2.1 147.9 2.1 184.9 0 35.9-1.7 67.7-9.9 93.9-36.2 26.2-26.2 34.4-58 36.2-93.9 2.1-37 2.1-147.8 0-184.8zM398.8 388c-7.8 19.6-22.9 34.7-42.6 42.6-29.5 11.7-99.5 9-132.1 9s-102.7 2.6-132.1-9c-19.6-7.8-34.7-22.9-42.6-42.6-11.7-29.5-9-99.5-9-132.1s-2.6-102.7 9-132.1c7.8-19.6 22.9-34.7 42.6-42.6 29.5-11.7 99.5-9 132.1-9s102.7-2.6 132.1 9c19.6 7.8 34.7 22.9 42.6 42.6 11.7 29.5 9 99.5 9 132.1s2.7 102.7-9 132.1z" />
                  </svg>
                </span>
              </div>
              <div>
                <span className="w-5">
                  <svg
                    className="fill-primary"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 512 512"
                  >
                    <path d="M459.37 151.716c.325 4.548.325 9.097.325 13.645 0 138.72-105.583 298.558-298.558 298.558-59.452 0-114.68-17.219-161.137-47.106 8.447.974 16.568 1.299 25.34 1.299 49.055 0 94.213-16.568 130.274-44.832-46.132-.975-84.792-31.188-98.112-72.772 6.498.974 12.995 1.624 19.818 1.624 9.421 0 18.843-1.3 27.614-3.573-48.081-9.747-84.143-51.98-84.143-102.985v-1.299c13.969 7.797 30.214 12.67 47.431 13.319-28.264-18.843-46.781-51.005-46.781-87.391 0-19.492 5.197-37.36 14.294-52.954 51.655 63.675 129.3 105.258 216.365 109.807-1.624-7.797-2.599-15.918-2.599-24.04 0-57.828 46.782-104.934 104.934-104.934 30.213 0 57.502 12.67 76.67 33.137 23.715-4.548 46.456-13.32 66.599-25.34-7.798 24.366-24.366 44.833-46.132 57.827 21.117-2.273 41.584-8.122 60.426-16.243-14.292 20.791-32.161 39.308-52.628 54.253z" />
                  </svg>
                </span>
              </div>
              <div className="w-3">
                <span>
                  <svg
                    className="fill-primary"
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 320 512"
                  >
                    <path d="M279.14 288l14.22-92.66h-88.91v-60.13c0-25.35 12.42-50.06 52.24-50.06h40.42V6.26S260.43 0 225.36 0c-73.22 0-121.08 44.38-121.08 124.72v70.62H22.89V288h81.39v224h100.17V288z" />
                  </svg>
                </span>
              </div>
              <div className="w-5">
                <span>
                  <svg className="fill-primary" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 448 512">
                    <path d="M100.28 448H7.4V148.9h92.88zM53.79 108.1C24.09 108.1 0 83.5 0 53.8a53.79 53.79 0 0 1 107.58 0c0 29.7-24.1 54.3-53.79 54.3zM447.9 448h-92.68V302.4c0-34.7-.7-79.2-48.29-79.2-48.29 0-55.69 37.7-55.69 76.7V448h-92.78V148.9h89.08v40.8h1.3c12.4-23.5 42.69-48.3 87.88-48.3 94 0 111.28 61.9 111.28 142.3V448z" />
                  </svg>
                </span>
              </div>
            </div>
            <div>
              <p className="text-primary text-lg font-semibold pb-2">
                Let’s help show the world how valuable you are! ______
              </p>
              <h1 className="w-2/3 text-7xl text-primary font-bold pb-4">
                Get Started with Us
              </h1>
              <button
                type="text"
                className=" text-lg bg-secondary text-white rounded-lg px-5 py-2"
              >
                Register now
              </button>
            </div>
          </div>
        </main>
      </div>
      <section className="bg-body_bg pt-10 px-40 p-20">
        <div className="flex px-10">
          <div className="flex flex-col pr-28  border-r-2 border-primary">
            <p className="text-primary">Total Users</p>
            <h1 className="text-2xl font-bold text-primary">178,705</h1>
          </div>
          <div className="flex flex-col pr-28 pl-28  border-r-2 border-primary">
            <p className="text-primary">Total Advert</p>
            <h1 className="text-2xl font-bold text-primary">61,455</h1>
          </div>
          <div className="flex flex-col pr-28 pl-28  border-r-2 border-primary">
            <p className="text-primary">Total EVP Agents</p>
            <h1 className="text-2xl font-bold text-primary">62,637</h1>
          </div>
          <div className="flex flex-col  pl-28   border-primary">
            <p className="text-primary">Total Requests</p>
            <h1 className="text-2xl font-bold text-primary">504,892</h1>
          </div>
        </div>
        <div className="mt-10 p-10 grid grid-cols-1 sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-2 gap-5">
          <div className="rounded overflow-hidden shadow-lg border border-secondary">
            <div className="pt-10 pb-20 px-20">
              <div className="font-bold text-xl mb-2 flex justify-center">
                <div className="w-20 h-20 mb-5 bg-secondary rounded-full flex justify-center items-center">
                  <span className="w-10 text-primary">
                    <svg
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 512 512"
                      className="fill-primary"
                    >
                      <path d="M320 336c0 8.844-7.156 16-16 16h-96C199.2 352 192 344.8 192 336V288H0v144C0 457.6 22.41 480 48 480h416c25.59 0 48-22.41 48-48V288h-192V336zM464 96H384V48C384 22.41 361.6 0 336 0h-160C150.4 0 128 22.41 128 48V96H48C22.41 96 0 118.4 0 144V256h512V144C512 118.4 489.6 96 464 96zM336 96h-160V48h160V96z" />
                    </svg>
                  </span>
                </div>
              </div>
              <div className="flex justify-center ">
                <p className="text-sm text-primary text-center">
                  Built with love for you. A PlugBay membership gives you
                  immense opportunities to showcase your skills
                </p>
              </div>
            </div>
          </div>

          <div className="rounded overflow-hidden shadow-lg border border-secondary">
            <div className="pt-10 pb-20 px-20">
              <div className="font-bold text-xl mb-2 flex justify-center">
                <div className="w-20 h-20 mb-5 bg-secondary rounded-full flex justify-center items-center">
                  <span className="w-10 text-primary">
                    <svg
                      className="fill-primary"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 640 512"
                    >
                      <path d="M319.9 320c57.41 0 103.1-46.56 103.1-104c0-57.44-46.54-104-103.1-104c-57.41 0-103.1 46.56-103.1 104C215.9 273.4 262.5 320 319.9 320zM369.9 352H270.1C191.6 352 128 411.7 128 485.3C128 500.1 140.7 512 156.4 512h327.2C499.3 512 512 500.1 512 485.3C512 411.7 448.4 352 369.9 352zM512 160c44.18 0 80-35.82 80-80S556.2 0 512 0c-44.18 0-80 35.82-80 80S467.8 160 512 160zM183.9 216c0-5.449 .9824-10.63 1.609-15.91C174.6 194.1 162.6 192 149.9 192H88.08C39.44 192 0 233.8 0 285.3C0 295.6 7.887 304 17.62 304h199.5C196.7 280.2 183.9 249.7 183.9 216zM128 160c44.18 0 80-35.82 80-80S172.2 0 128 0C83.82 0 48 35.82 48 80S83.82 160 128 160zM551.9 192h-61.84c-12.8 0-24.88 3.037-35.86 8.24C454.8 205.5 455.8 210.6 455.8 216c0 33.71-12.78 64.21-33.16 88h199.7C632.1 304 640 295.6 640 285.3C640 233.8 600.6 192 551.9 192z" />
                    </svg>
                  </span>
                </div>
              </div>
              <div className="flex justify-center ">
                <p className="text-sm text-primary text-center">
                  Looking for more workers or service providers? Use plugbay to
                  bring workers
                </p>
              </div>
            </div>
          </div>

          <div className="rounded overflow-hidden shadow-lg border border-secondary">
            <div className="pt-10 pb-20 px-20">
              <div className="font-bold text-xl mb-2 flex justify-center">
                <div className="w-20 h-20 mb-5 bg-secondary rounded-full flex justify-center items-center">
                  <span className="w-10 text-primary">
                    <svg
                      className="fill-primary"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 512 512"
                    >
                      <path d="M0 190.9V185.1C0 115.2 50.52 55.58 119.4 44.1C164.1 36.51 211.4 51.37 244 84.02L256 96L267.1 84.02C300.6 51.37 347 36.51 392.6 44.1C461.5 55.58 512 115.2 512 185.1V190.9C512 232.4 494.8 272.1 464.4 300.4L283.7 469.1C276.2 476.1 266.3 480 256 480C245.7 480 235.8 476.1 228.3 469.1L47.59 300.4C17.23 272.1 .0003 232.4 .0003 190.9L0 190.9z" />
                    </svg>
                  </span>
                </div>
              </div>
              <div className="flex justify-center ">
                <p className="text-sm text-primary text-center">
                  Built with love for you. A PlugBay membership gives you
                  immense opportunities to showcase your skills
                </p>
              </div>
            </div>
          </div>

          <div className="rounded overflow-hidden shadow-lg border border-secondary">
            <div className="pt-10 pb-20 px-20">
              <div className="font-bold text-xl mb-2 flex justify-center">
                <div className="w-20 h-20 mb-5 bg-secondary rounded-full flex justify-center items-center">
                  <span className="w-10 text-primary">
                    <svg
                      className="fill-primary"
                      xmlns="http://www.w3.org/2000/svg"
                      viewBox="0 0 512 512"
                    >
                      <path d="M480 179.6C498.6 188.4 512 212.1 512 240C512 267.9 498.6 291.6 480 300.4V448C480 460.9 472.2 472.6 460.2 477.6C448.3 482.5 434.5 479.8 425.4 470.6L381.7 426.1C333.7 378.1 268.6 352 200.7 352H192V480C192 497.7 177.7 512 160 512H96C78.33 512 64 497.7 64 480V352C28.65 352 0 323.3 0 288V192C0 156.7 28.65 128 64 128H200.7C268.6 128 333.7 101 381.7 53.02L425.4 9.373C434.5 .2215 448.3-2.516 460.2 2.437C472.2 7.39 480 19.06 480 32V179.6zM200.7 192H192V288H200.7C280.5 288 357.2 317.8 416 371.3V108.7C357.2 162.2 280.5 192 200.7 192V192z" />
                    </svg>
                  </span>
                </div>
              </div>
              <div className="flex justify-center ">
                <p className="text-sm text-primary text-center">
                  Advertise with freedom at last…no Internet, smart phone or sms
                  credit needed.
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
